// @generated by dung beetle from https://raw.githubusercontent.com/grMLEqomlkkU5Eeinz4brIrOVCUCkJuN/newYorkTimes-dung-beetle/refs/heads/master/nyt3.json. Do not edit.
//
// Re-running the generator rewrites this file. A resource module without
// this banner is left alone, so hand-written ones are safe here.

import type { Operation, QueryValue } from "../operation.js";
import type { paths } from "../schema.js";

/** The part of a documented query type that this client can put on a URL. */
type Sendable<T> = Extract<T, QueryValue>;

type GetNameSpecificConceptJsonWirePath = NonNullable<paths["/name/{concept-type}/{specific-concept}.json"]["get"]["parameters"]["path"]>;

type GetNameSpecificConceptJsonWireQuery = NonNullable<paths["/name/{concept-type}/{specific-concept}.json"]["get"]["parameters"]["query"]>;

/** Query accepted by {@link getNameSpecificConceptJson}. */
export interface GetNameSpecificConceptJsonQuery {
	/**
	 * "all" or comma-separated list of specific optional fields: pages, ticker_symbol, links, taxonomy, combinations, geocodes, article_list, scope_notes, search_api_query
	 *
	 * Optional fields are returned in result_set. They are briefly explained here:
	 *
	 * pages: A list of topic pages associated with a specific concept.
	 * ticker_symbol: If this concept is a publicly traded company, this field contains the ticker symbol.
	 * links: A list of links from this concept to external data resources.
	 * taxonomy: For descriptor concepts, this field returns a list of taxonomic relations to other concepts.
	 * combinations: For descriptor concepts, this field returns a list of the specific meanings tis concept takes on when combined with other concepts.
	 * geocodes: For geographic concepts, the full GIS record from geonames.
	 * article_list: A list of up to 10 articles associated with this concept.
	 * scope_notes: Scope notes contains clarifications and meaning definitions that explicate the relationship between the concept and an article.
	 * search_api_query: Returns the request one would need to submit to the Article Search API to obtain a list of articles annotated with this concept.
	 *
	 */
	readonly fields?: Sendable<GetNameSpecificConceptJsonWireQuery["fields"]>;

	/** Precedes the search term string. Used in a Search Query. Except for &lt;specific_concept_name&gt;, Search Query will take the required parameters listed above (&lt;concept_type&gt;, &lt;concept_uri&gt;, &lt;article_uri&gt;) as an optional_parameter in addition to the query=&lt;query_term&gt;. */
	readonly query: Sendable<GetNameSpecificConceptJsonWireQuery["query"]>;
}

/** What {@link getNameSpecificConceptJson} resolves to. */
export type GetNameSpecificConceptJsonResponse =
	paths["/name/{concept-type}/{specific-concept}.json"]["get"]["responses"][200]["content"]["application/json"];

/**
 * `GET /name/{concept-type}/{specific-concept}.json`
 *
 * @security apikey: query parameter `api-key`, which needs a transport decorator since the client sends no query of its own
 */
export function getNameSpecificConceptJson(
	conceptType: GetNameSpecificConceptJsonWirePath["concept-type"],
	specificConcept: GetNameSpecificConceptJsonWirePath["specific-concept"],
	query: GetNameSpecificConceptJsonQuery,
): Operation<GetNameSpecificConceptJsonResponse> {
	return {
		method: "GET",
		path: `/name/${encodeURIComponent(String(conceptType))}/${encodeURIComponent(String(specificConcept))}.json`,
		query: {
			fields: query.fields,
			query: query.query,
		},
	};
}
