// @generated by dung beetle from https://raw.githubusercontent.com/grMLEqomlkkU5Eeinz4brIrOVCUCkJuN/newYorkTimes-dung-beetle/refs/heads/master/nyt3.json. Do not edit.
//
// Every type the document declares. Resource modules alias into it, so a
// name here is only public where one of them exports it.

export interface paths {
    readonly "/name/{concept-type}/{specific-concept}.json": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query: {
                    /**
                     * @description "all" or comma-separated list of specific optional fields: pages, ticker_symbol, links, taxonomy, combinations, geocodes, article_list, scope_notes, search_api_query
                     *
                     *     Optional fields are returned in result_set. They are briefly explained here:
                     *
                     *     pages: A list of topic pages associated with a specific concept.
                     *     ticker_symbol: If this concept is a publicly traded company, this field contains the ticker symbol.
                     *     links: A list of links from this concept to external data resources.
                     *     taxonomy: For descriptor concepts, this field returns a list of taxonomic relations to other concepts.
                     *     combinations: For descriptor concepts, this field returns a list of the specific meanings tis concept takes on when combined with other concepts.
                     *     geocodes: For geographic concepts, the full GIS record from geonames.
                     *     article_list: A list of up to 10 articles associated with this concept.
                     *     scope_notes: Scope notes contains clarifications and meaning definitions that explicate the relationship between the concept and an article.
                     *     search_api_query: Returns the request one would need to submit to the Article Search API to obtain a list of articles annotated with this concept.
                     */
                    readonly fields?: "all" | "pages" | "ticker_symbol" | "links" | "taxonomy" | "combinations" | "geocodes" | "article_list" | "scope_notes" | "search_api_query";
                    /** @description Precedes the search term string. Used in a Search Query. Except for &lt;specific_concept_name&gt;, Search Query will take the required parameters listed above (&lt;concept_type&gt;, &lt;concept_uri&gt;, &lt;article_uri&gt;) as an optional_parameter in addition to the query=&lt;query_term&gt;. */
                    readonly query: string;
                };
                readonly header?: never;
                readonly path: {
                    /** @description The type of the concept, used for Constructing a Semantic API Request by Concept Type and Specific Concept Name. The parameter is defined as a name-value pair, as in "concept_type=[nytd_geo|nytd_per|nytd_org|nytd_des]". */
                    readonly "concept-type": "nytd_geo" | "nytd_per" | "nytd_org" | "nytd_des";
                    /** @description The name of the concept, used for Constructing a Semantic API Request by Concept Type and Specific Concept Name. The parameter is defined in the URI path, as the element immediately preceding ".json" like with "Baseball.json". */
                    readonly "specific-concept": string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description An array of Concepts */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly status?: string;
                            readonly copyright?: string;
                            readonly num_results?: number;
                            readonly results?: readonly components["schemas"]["Concept"][];
                        };
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/search.json": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: {
            readonly parameters: {
                readonly query: {
                    /** @description Precedes the search term string. Used in a Search Query. Except for &lt;specific_concept_name&gt;, Search Query will take the required parameters listed above (&lt;concept_type&gt;, &lt;concept_uri&gt;, &lt;article_uri&gt;) as an optional_parameter in addition to the query=&lt;query_term&gt;. */
                    readonly query: string;
                    /** @description Integer value for the index count from the first concept to the last concept, sorted alphabetically. Used in a Search Query. A Search Query will return up to 10 concepts in its results. */
                    readonly offset?: number;
                    /**
                     * @description "all" or comma-separated list of specific optional fields: pages, ticker_symbol, links, taxonomy, combinations, geocodes, article_list, scope_notes, search_api_query
                     *
                     *     Optional fields are returned in result_set. They are briefly explained here:
                     *
                     *     pages: A list of topic pages associated with a specific concept.
                     *     ticker_symbol: If this concept is a publicly traded company, this field contains the ticker symbol.
                     *     links: A list of links from this concept to external data resources.
                     *     taxonomy: For descriptor concepts, this field returns a list of taxonomic relations to other concepts.
                     *     combinations: For descriptor concepts, this field returns a list of the specific meanings tis concept takes on when combined with other concepts.
                     *     geocodes: For geographic concepts, the full GIS record from geonames.
                     *     article_list: A list of up to 10 articles associated with this concept.
                     *     scope_notes: Scope notes contains clarifications and meaning definitions that explicate the relationship between the concept and an article.
                     *     search_api_query: Returns the request one would need to submit to the Article Search API to obtain a list of articles annotated with this concept.
                     */
                    readonly fields?: "all" | "pages" | "ticker_symbol" | "links" | "taxonomy" | "combinations" | "geocodes" | "article_list" | "scope_notes" | "search_api_query";
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description An array of Concepts */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": {
                            readonly status?: string;
                            readonly copyright?: string;
                            readonly num_results?: number;
                            readonly results?: readonly components["schemas"]["ConceptRelation"][];
                        };
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly Concept: {
            readonly concept_id?: number;
            readonly concept_name?: string;
            readonly is_times_tag?: number;
            readonly concept_status?: string;
            readonly vernacular?: string;
            readonly concept_type?: string;
            readonly concept_created?: string;
            readonly concept_updated?: string;
            readonly taxonomy?: readonly {
                readonly source_concept_id?: number;
                readonly target_concept_id?: number;
                readonly source_concept_name?: string;
                readonly target_concept_name?: string;
                readonly source_concept_type?: string;
                readonly target_concept_type?: string;
                readonly source_concept_vernacular?: string;
                readonly target_concept_vernacular?: string;
                readonly taxonomic_relation?: string;
                readonly taxonomic_verification_status?: string;
            }[];
            readonly links?: readonly {
                readonly concept_id?: number;
                readonly concept_name?: string;
                readonly concept_status?: string;
                readonly is_times_tag?: number;
                readonly concept_type?: string;
                readonly link_id?: number;
                readonly relation?: string;
                readonly link?: string;
                readonly link_type?: string;
                readonly mapping_type?: string;
            }[];
            readonly search_api_query?: string;
            readonly article_list?: {
                readonly results?: readonly {
                    readonly body?: string;
                    readonly byline?: string;
                    readonly concepts?: {
                        readonly nytd_des?: readonly string[];
                        readonly nytd_org?: readonly string[];
                        readonly nytd_per?: readonly string[];
                    };
                    readonly date?: string;
                    readonly document_type?: string;
                    readonly title?: string;
                    readonly type_of_material?: string;
                    readonly url?: string;
                }[];
                readonly total?: number;
            };
            readonly scope_notes?: readonly {
                readonly scope_note?: string;
                readonly scope_note_name?: string;
                readonly scope_note_type?: string;
            }[];
            readonly combinations?: readonly {
                readonly combination_source_concept_id?: number;
                readonly combination_source_concept_name?: string;
                readonly combination_source_concept_type?: string;
                readonly combination_target_concept_id?: number;
                readonly combination_target_concept_name?: string;
                readonly combination_target_concept_type?: string;
                readonly combination_note?: string;
            }[];
            readonly ancestors?: readonly components["schemas"]["ConceptRelation"][];
            readonly descendants?: readonly components["schemas"]["ConceptRelation"][];
        };
        readonly ConceptRelation: {
            readonly concept_id?: number;
            readonly concept_name?: string;
            readonly is_times_tag?: number;
            readonly concept_status?: string;
            readonly vernacular?: string;
            readonly concept_type?: string;
            readonly concept_created?: string;
            readonly concept_updated?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
